package vista;

import controlador.Controlador;
import java.awt.Color;
import java.time.DayOfWeek;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAdjusters;
import java.time.temporal.WeekFields;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vicent
 */
public class GestList extends javax.swing.JDialog {

   Controlador c = new Controlador();
   int idUser = 0;

    public GestList(java.awt.Frame parent, boolean modal, int idUser) {
        super(parent, modal);
        initComponents();
        this.idUser = idUser;
        
        this.getContentPane().setBackground(Color.white);
        
        CargarCBoxList();
        setDatosFecha();
        CargarTablaUsuarios();
    }
    
        public GestList(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
        
        
        public void CargarCBoxList(){
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        ArrayList<String> listas = c.getAdminListsName(idUser);        
        
            for ( int i =0; i < listas.size(); i++ ){

                model.addElement(listas.get(i));
            }
            cBoxList.setModel(model);
        }
        
        
        public void CargarTablaUsuarios(){
        
        int selectedIndex = cBoxList.getSelectedIndex();
        ArrayList<String> nombres = c.getListParticipants(idUser, selectedIndex);
        
        
        String[] columnas= {"nombre"};
        
        DefaultTableModel dtm = new DefaultTableModel(null, columnas);
        
             for ( int i =0; i < nombres.size(); i++ ){
            
                dtm.addRow(new Object[]{nombres.get(i)});
            }
            usersList.setDefaultEditor(Object.class, null);
            usersList.setRowHeight(20);
            usersList.setModel(dtm);
      
            }
        
        public void setDatosFecha(){
        
        int selectedIndex = cBoxList.getSelectedIndex();
        ArrayList<String> infoFecha = c.getInfoPedido(idUser, selectedIndex);
        
        if (infoFecha.get(0) != null){
        
            String fechaEnvio = infoFecha.get(0);
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            LocalDateTime fecha = LocalDateTime.parse(fechaEnvio, formatter);
            int dayOfWeek = (fecha.getDayOfWeek().getValue()) - 1;
            
            cBoxDia.setSelectedIndex(dayOfWeek);
            
            formatter = DateTimeFormatter.ofPattern("dd-MM-yy HH:mm");
            
            lblFecha.setText("Pedido: "+formatter.format(fecha)+"h");
            
        } else {
            cBoxDia.setSelectedIndex(0);
            lblFecha.setText("");
        }
        
        spnPeriod.setValue(Integer.valueOf(infoFecha.get(1))/7);
        
        chBoxVaciar.setSelected(Boolean.valueOf(infoFecha.get(2)));
        
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

lblEliminar = new javax.swing.JLabel();
cBoxList = new javax.swing.JComboBox<>();
btnAdd = new javax.swing.JButton();
lblAdd = new javax.swing.JLabel();
TFieldAdd = new javax.swing.JTextField();
btnDeleteList = new javax.swing.JButton();
jSeparator1 = new javax.swing.JSeparator();
lblSelec = new javax.swing.JLabel();
lblRealizar = new javax.swing.JLabel();
btnAgregar = new javax.swing.JButton();
lblMiembros = new javax.swing.JLabel();
jScrollPane1 = new javax.swing.JScrollPane();
usersList = new javax.swing.JTable();
TFusuarios = new javax.swing.JTextField();
btnFecha = new javax.swing.JButton();
btnQuitar = new javax.swing.JButton();
chBoxVaciar = new javax.swing.JCheckBox();
cBoxDia = new javax.swing.JComboBox<>();
lblRecibir = new javax.swing.JLabel();
lblSemana = new javax.swing.JLabel();
spnPeriod = new javax.swing.JSpinner();
lblFecha = new javax.swing.JLabel();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Gestión Listas");

lblEliminar.setText("Eliminar lista");

cBoxList.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
cBoxListActionPerformed(evt);
}
});

btnAdd.setText("+");
btnAdd.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnAddActionPerformed(evt);
}
});

lblAdd.setText("Crear lista");

btnDeleteList.setText("-");
btnDeleteList.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnDeleteListActionPerformed(evt);
}
});

lblSelec.setText("Seleccionar lista");

lblRealizar.setText("Realizar pedido:");

btnAgregar.setText("Agregar");
btnAgregar.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnAgregarActionPerformed(evt);
}
});

lblMiembros.setText("Miembros");

usersList.setModel(new javax.swing.table.DefaultTableModel(
new Object [][] {

},
new String [] {
"nombres"
}
));
jScrollPane1.setViewportView(usersList);

btnFecha.setText("Aceptar");
btnFecha.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnFechaActionPerformed(evt);
}
});

btnQuitar.setText("Quitar");
btnQuitar.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnQuitarActionPerformed(evt);
}
});

chBoxVaciar.setText("Vaciar tras pedido");
chBoxVaciar.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
chBoxVaciarActionPerformed(evt);
}
});

cBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado" }));

lblRecibir.setText("Recibir cada:");

lblSemana.setText("semana(s)");

spnPeriod.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));

lblFecha.setFont(new java.awt.Font("Noto Sans Medium", 0, 12)); // NOI18N
lblFecha.setText("pedido: 21-05-24 08:00h");

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(37, 37, 37)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(1, 1, 1)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
.addGroup(layout.createSequentialGroup()
.addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(lblEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(btnDeleteList, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addGroup(layout.createSequentialGroup()
.addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(31, 31, 31)
.addComponent(TFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(18, 18, 18)
.addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createSequentialGroup()
.addComponent(lblSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(1, 1, 1)
.addComponent(cBoxList, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
.addComponent(lblMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(lblRealizar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
.addComponent(lblRecibir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addGroup(layout.createSequentialGroup()
.addGap(14, 14, 14)
.addComponent(cBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createSequentialGroup()
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(chBoxVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGroup(layout.createSequentialGroup()
.addComponent(spnPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(18, 18, 18)
.addComponent(lblSemana)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(btnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
.addGap(0, 0, Short.MAX_VALUE)))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
.addComponent(TFusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
.addGap(27, 27, 27)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
.addComponent(btnQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addGap(40, 40, 40))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(45, 45, 45)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(lblAdd)
.addComponent(TFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(lblMiembros)
.addComponent(TFusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(30, 30, 30)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(40, 40, 40)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(lblSelec)
.addComponent(cBoxList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(btnDeleteList, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(lblEliminar)
.addComponent(lblFecha))
.addGap(60, 60, 60)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(lblRealizar)
.addComponent(cBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 46, Short.MAX_VALUE)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(lblRecibir)
.addComponent(spnPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(lblSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(btnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(30, 30, 30)
.addComponent(chBoxVaciar))
.addGroup(layout.createSequentialGroup()
.addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(0, 0, Short.MAX_VALUE))
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
.addGap(61, 61, 61))
);

pack();
setLocationRelativeTo(null);
}// </editor-fold>//GEN-END:initComponents

private void chBoxVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBoxVaciarActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_chBoxVaciarActionPerformed

private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

    String nombreUsu = TFusuarios.getText();
    int selectedIndex = cBoxList.getSelectedIndex();
    c.AgregarUsuList(idUser, nombreUsu, selectedIndex);
    CargarTablaUsuarios();
}//GEN-LAST:event_btnAgregarActionPerformed

private void btnDeleteListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteListActionPerformed

    int selectedIndex = cBoxList.getSelectedIndex();
    c.DeleteList(idUser, selectedIndex);
    CargarCBoxList();
}//GEN-LAST:event_btnDeleteListActionPerformed

private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed

     int selectedIndex = cBoxList.getSelectedIndex();
    String nomUsu = usersList.getModel().getValueAt(usersList.getSelectedRow(), 0).toString();
    c.QuitarUsuList(idUser, selectedIndex, nomUsu);
    CargarTablaUsuarios();
}//GEN-LAST:event_btnQuitarActionPerformed

private void cBoxListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxListActionPerformed

    setDatosFecha();
    CargarTablaUsuarios();
}//GEN-LAST:event_cBoxListActionPerformed

private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed

     int dia = cBoxDia.getSelectedIndex();
     int periodo = (int) spnPeriod.getValue() * 7;
     boolean vaciar = chBoxVaciar.isSelected();
     int selectedList= cBoxList.getSelectedIndex();     
         
     LocalDateTime currentDate = LocalDateTime.now();
     DateTimeFormatter unicoHoy = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
     DateTimeFormatter periodico = DateTimeFormatter.ofPattern("yyyy-MM-dd");
     String fechaPedido = null; 
     
     int dayOfWeek = (currentDate.getDayOfWeek().getValue()) - 1;
     
     if (periodo == 0 && dia == dayOfWeek){
       
        currentDate = LocalDateTime.now().plusMinutes(1);
        fechaPedido = currentDate.format(unicoHoy);
        
       } else {
     
      switch(dia) {
      
      case 0: currentDate = currentDate.with(TemporalAdjusters.nextOrSame(DayOfWeek.MONDAY));
                    break;
                    
      case 1: currentDate = currentDate.with(TemporalAdjusters.nextOrSame(DayOfWeek.TUESDAY));
                    break;
                    
      case 2: currentDate = currentDate.with(TemporalAdjusters.nextOrSame(DayOfWeek.WEDNESDAY));
                    break;
                    
      case 3: currentDate = currentDate.with(TemporalAdjusters.nextOrSame(DayOfWeek.THURSDAY));
                    break;
                    
      case 4: currentDate = currentDate.with(TemporalAdjusters.nextOrSame(DayOfWeek.FRIDAY));
                    break;              
       }
          
       fechaPedido = currentDate.format(periodico)+" 08:00";
       }
       
       c.UpdateFechaList(fechaPedido, periodo, vaciar, idUser, selectedList);
       setDatosFecha();
         
}//GEN-LAST:event_btnFechaActionPerformed

private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
     String titulo = TFieldAdd.getText();
    c.CrearLista(idUser, titulo);
    CargarCBoxList();
}//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestList dialog = new GestList(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JTextField TFieldAdd;
private javax.swing.JTextField TFusuarios;
private javax.swing.JButton btnAdd;
private javax.swing.JButton btnAgregar;
private javax.swing.JButton btnDeleteList;
private javax.swing.JButton btnFecha;
private javax.swing.JButton btnQuitar;
private javax.swing.JComboBox<String> cBoxDia;
private javax.swing.JComboBox<String> cBoxList;
private javax.swing.JCheckBox chBoxVaciar;
private javax.swing.JScrollPane jScrollPane1;
private javax.swing.JSeparator jSeparator1;
private javax.swing.JLabel lblAdd;
private javax.swing.JLabel lblEliminar;
private javax.swing.JLabel lblFecha;
private javax.swing.JLabel lblMiembros;
private javax.swing.JLabel lblRealizar;
private javax.swing.JLabel lblRecibir;
private javax.swing.JLabel lblSelec;
private javax.swing.JLabel lblSemana;
private javax.swing.JSpinner spnPeriod;
private javax.swing.JTable usersList;
// End of variables declaration//GEN-END:variables
}
